version: '3.9'
services:
  app:
    image: fajjarnr/bwf-micro-backend:service-payment
    container_name: bwf-service-payment
    environment:
      - APP_NAME=service_payment
      - APP_KEY=base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
      - APP_URL=http://bwf-service-payment:8001
      - DB_CONNECTION=mysql
      - DB_HOST=bwf-micro.cyh0sfq8vv2a.ap-southeast-3.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=service_payment
      - DB_USERNAME=admin
      - DB_PASSWORD=rahasia123
      - MIDTRANS_SERVER_KEY="Mid-server-osPlAQkCeW4BYz5_KP-gO7O-"
      - MIDTRANS_CLIENT_KEY="Mid-client-ptBFVvqK12FuFSJd"
      - MIDTRANS_IS_PRODUCTION=false
      - MIDTRANS_IS_SANITIZED=false
      - MIDTRANS_IS_3DS=true
      - SERVICE_COURSE_URL=bwf-service-course
    restart: always
    tty: true
    ports:
      - 8001:8001
    networks:
      - service-payment-network

networks:
  service-payment-network:
