apiVersion: v1
kind: ConfigMap
metadata:
  name: env-service-payment
  namespace: bwf
data:
  APP_NAME: "service_course"
  APP_KEY: "base64:6zrLF/wEs3hO4AlX+BReJ803ec4zR//FWEOz6ZSgYuw="
  APP_URL: http://bwf-service-order-payment

  LOG_CHANNEL: stack
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_DATABASE: service_payment
  DB_USERNAME: root
  DB_PASSWORD: rahasia

  MIDTRANS_SERVER_KEY: "Mid-server-osPlAQkCeW4BYz5_KP-gO7O-"
  MIDTRANS_CLIENT_KEY: "Mid-client-ptBFVvqK12FuFSJd"
  MIDTRANS_IS_PRODUCTION: "false"
  MIDTRANS_IS_SANITIZED: "false"
  MIDTRANS_IS_3DS: "true"

  SERVICE_COURSE_URL: http://bwf-service-course

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwf-service-order-payment
  namespace: bwf
  labels:
    app: bwf-service-order-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwf-service-order-payment
  template:
    metadata:
      labels:
        app: bwf-service-order-payment
    spec:
      containers:
        - name: bwf-service-order-payment
          image: "fajjarnr/bwf-service-order-payment:latest"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-service-payment
